# Generated by Django 4.1.1 on 2022-09-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='name',
            new_name='username',
        ),
    ]
